version: "3,8"

volumes:
  api-data:

services:
  api:
    build:
      context: .
      dockerfile: devops/docker/backend/Dockerfile
    command:  uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    # ports:
    #   - 8001:8000
    networks:
      - test_network
    user: worker

  apifront:
    build:
      context: .
      dockerfile: devops/docker/frontend/Dockerfile
    # ports:
    #   - 8080:8080
    networks:
      - test_network
    # environment:
    #   # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
    #   - NGINX_HOST=localhost
    #   - NGINX_PORT=80
    user: nginx

  apiproxy:
    build:
      context: .
      dockerfile: devops/docker/proxy/Dockerfile
    ports:
      - 80:80
      - 8081:8081
      - 8082:8082
    networks:
      - test_network
    environment:
       - VIRTUAL_HOST=fastapi.local
    #   # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
    #   - NGINX_HOST=localhost
    #   - NGINX_PORT=80
    user: nginx


  apidb:
    container_name: fapi-postgresdb
    image: postgres:latest
    networks:
      - test_network
    restart: unless-stopped
    volumes:
      - api-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres



networks:
  test_network:

