version: '3.8'

volumes:
  fastapi-data:

networks:
  fastapi:

services:
  fastapi:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #platform: linux/amd64
    init: true
    container_name: fastapi-dev
    networks:
      - fastapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an version of Java: 11, 17.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 3.10-buster
        # Options
        INSTALL_MAVEN: "false"
        MAVEN_VERSION: ""
        INSTALL_GRADLE: "false"
        GRADLE_VERSION: ""
        NODE_VERSION: "lts/*"
        USE_MOBY: "false"
        INSTALL_ZSH: "true"
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: postgresdb

    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
      - ~/.kube:/home/vscode/.kube
      - ~/.ssh:/home/vscode/.ssh
      - ~/.gitconfig:/home/vscode/.gitconfig
      - ~/.aws:/home/vscode/.aws


    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    # Uncomment the next line to use a non-root user for all processes.
    user: vscode


  fastapidb:
    container_name: fastapi-postgresdb
    image: postgres:latest
    networks:
      - fastapi
    restart: unless-stopped
    volumes:
      - fastapi-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
