apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reverse
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reverse
            port:
              number: 8080

